In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from catboost import CatBoostClassifier
from catboost import CatBoostRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
data_train = pd.read_csv('train.csv')
data_test = pd.read_csv('test.csv')
data_col = pd.read_csv('test.csv')

In [3]:
data_train.columns

Index(['id', 'person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income', 'cb_person_default_on_file',
       'cb_person_cred_hist_length', 'loan_status'],
      dtype='object')

In [4]:
data_train.isnull().sum()

id                            0
person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
loan_status                   0
dtype: int64

In [5]:
data_train = data_train.drop('id', axis = 1)
# data_test = data_test.drop('id', axis = 1)
data_col = pd.read_csv('test.csv')

In [6]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  58645 non-null  int64
 1   person_income               58645 non-null  int64
 2   person_home_ownership       58645 non-null  object
 3   person_emp_length           58645 non-null  float64
 4   loan_intent                 58645 non-null  object
 5   loan_grade                  58645 non-null  object
 6   loan_amnt                   58645 non-null  int64
 7   loan_int_rate               58645 non-null  float64
 8   loan_percent_income         58645 non-null  float64
 9   cb_person_default_on_file   58645 non-null  object
 10  cb_person_cred_hist_length  58645 non-null  int64
 11  loan_status                 58645 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 5.4+ MB

In [7]:
data_train.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0

In [8]:
data_train['total_intrest'] = data_train['loan_amnt'] * (data_train['loan_int_rate']/100)
data_test['total_intrest'] = data_test['loan_amnt'] * (data_test['loan_int_rate']/100)

In [9]:
data_train['total_intrest'] = data_train['loan_amnt'] + data_train['total_intrest']
data_test['total_intrest'] = data_test['loan_amnt'] + data_test['total_intrest']

In [10]:
data_train = data_train.drop('loan_amnt', axis = 1)
data_train = data_train.drop('loan_int_rate', axis = 1)

data_test = data_test.drop('loan_amnt', axis = 1)
data_test = data_test.drop('loan_int_rate', axis = 1)

In [11]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  58645 non-null  int64
 1   person_income               58645 non-null  int64
 2   person_home_ownership       58645 non-null  object
 3   person_emp_length           58645 non-null  float64
 4   loan_intent                 58645 non-null  object
 5   loan_grade                  58645 non-null  object
 6   loan_percent_income         58645 non-null  float64
 7   cb_person_default_on_file   58645 non-null  object
 8   cb_person_cred_hist_length  58645 non-null  int64
 9   loan_status                 58645 non-null  int64
 10  total_intrest               58645 non-null  float64
dtypes: float64(3), int64(4), object(4)
memory usage: 4.9+ MB

In [12]:
from sklearn.preprocessing import LabelEncoder


columns_to_encode = ['person_home_ownership', 'loan_intent', 'loan_grade', 'cb_person_default_on_file']


le = LabelEncoder()

for col in columns_to_encode:

    le.fit(data_train[col])
    
    data_train[col] = le.transform(data_train[col])
    data_test[col] = le.transform(data_test[col])

In [13]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  58645 non-null  int64
 1   person_income               58645 non-null  int64
 2   person_home_ownership       58645 non-null  int64
 3   person_emp_length           58645 non-null  float64
 4   loan_intent                 58645 non-null  int64
 5   loan_grade                  58645 non-null  int64
 6   loan_percent_income         58645 non-null  float64
 7   cb_person_default_on_file   58645 non-null  int64
 8   cb_person_cred_hist_length  58645 non-null  int64
 9   loan_status                 58645 non-null  int64
 10  total_intrest               58645 non-null  float64
dtypes: float64(3), int64(8)
memory usage: 4.9 MB

In [14]:
data_train = data_train[['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_percent_income',
       'cb_person_default_on_file', 'cb_person_cred_hist_length',
       'total_intrest', 'loan_status']]

In [15]:
data_test = data_test[['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_percent_income',
       'cb_person_default_on_file', 'cb_person_cred_hist_length',
       'total_intrest']]

In [16]:
X, y = data_train.to_numpy()[:,:-1], data_train.to_numpy()[:,-1]

In [17]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X)
X_test_scaled = scaler.transform(data_test)

pca = PCA(n_components=0.95)  # Retain 95% of variance
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

print(f"Explained variance ratio of the PCA components: {pca.explained_variance_ratio_}")
print(f"Number of components after PCA: {pca.n_components_}")

Explained variance ratio of the PCA components: [0.20299806 0.18618974 0.15589712 0.13019521 0.0993095  0.0887753
 0.06651693 0.04319935]
Number of components after PCA: 8

/Users/vivekrambha/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_pca, y, test_size = 0.2, random_state = 42)

In [19]:
X_train_pca

array([[ 1.07334314,  0.90587166, -2.10893851, ..., -0.45212819,
        -0.2524167 ,  0.14493572],
       [-1.0149481 , -1.09913939, -0.45017942, ...,  0.29772002,
         0.48612912,  1.04162527],
       [ 0.78991248, -0.19646258, -0.49776933, ...,  1.05193793,
         0.21558893, -0.47826487],
       ...,
       [-1.5644059 ,  0.14851233, -0.28080005, ...,  0.7809809 ,
         1.02454976,  1.56213334],
       [-1.52658076, -1.13696439, -0.47301284, ...,  0.06251478,
         0.16691733, -0.49633789],
       [ 0.60232071,  0.45052502,  1.01375273, ..., -0.80553068,
        -1.13306518,  0.28578156]])

In [20]:
model = CatBoostRegressor(iterations=1000, learning_rate=0.5, depth=4, verbose=200)

In [21]:
model.fit(X_train, y_train)

0:	learn: 0.3097386	total: 59.6ms	remaining: 59.5s
200:	learn: 0.2231908	total: 276ms	remaining: 1.1s
400:	learn: 0.2105088	total: 485ms	remaining: 724ms
600:	learn: 0.2013594	total: 697ms	remaining: 462ms
800:	learn: 0.1936247	total: 905ms	remaining: 225ms
999:	learn: 0.1871530	total: 1.12s	remaining: 0us

In [22]:
y_pred = model.predict(X_test)

In [23]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared: {r2:.2f}")

Mean Squared Error: 0.06
R-squared: 0.53

In [24]:
X_test = data_test.iloc[:,1:].to_numpy()

In [25]:
data_test['loan_status'] = model.predict(X_test_pca)

In [26]:
data_col['loan_status'] = data_test['loan_status']

In [27]:
data_col.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,58645,23,69000,RENT,3.0,HOMEIMPROVEMENT,F,25000,15.76,0.36,N,2,0.604379
1,58646,26,96000,MORTGAGE,6.0,PERSONAL,C,10000,12.68,0.10,Y,4,0.086071
2,58647,26,30000,RENT,5.0,VENTURE,E,4000,17.19,0.13,Y,2,0.208660
3,58648,33,50000,RENT,4.0,DEBTCONSOLIDATION,A,7000,8.90,0.14,N,7,0.038417
4,58649,26,102000,MORTGAGE,8.0,HOMEIMPROVEMENT,D,15000,16.32,0.15,Y,4,0.221400

In [28]:
data_col[['id', 'loan_status']].to_csv('submission.csv', index = False)

In [29]:
data_test.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,total_intrest,loan_status
0,23,69000,3,3.0,2,5,0.36,0,2,28940.0,0.604379
1,26,96000,0,6.0,4,2,0.10,1,4,11268.0,0.086071
2,26,30000,3,5.0,5,4,0.13,1,2,4687.6,0.208660
3,33,50000,3,4.0,0,0,0.14,0,7,7623.0,0.038417
4,26,102000,0,8.0,2,3,0.15,1,4,17448.0,0.221400

In [30]:
data_test['loan_status']

0        0.604379
1        0.086071
2        0.208660
3        0.038417
4        0.221400
           ...
39093    0.090384
39094   -0.007653
39095    0.144822
39096    0.081108
39097    1.126474
Name: loan_status, Length: 39098, dtype: float64